# Generated by Django 4.1.2 on 2022-10-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0003_customusermodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueModel',
            fields=[
                ('issue', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('mentorName', models.CharField(max_length=50)),
                ('mentorId', models.CharField(max_length=32)),
                ('assigneeName', models.CharField(max_length=50)),
                ('assigneeId', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Issue',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
