# Generated by Django 4.1.2 on 2022-10-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0004_issuemodel_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Announcement',
            },
        ),
    ]
