# Generated by Django 4.1.2 on 2022-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0004_issuemodel_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='assigneeId',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='issuemodel',
            name='assigneeName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issuemodel',
            name='issue',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
