# Generated by Django 4.1.2 on 2022-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0004_issuemodel_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoucementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
