# Generated by Django 4.1.2 on 2022-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0005_alter_issuemodel_assigneeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='assigneeId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='issuemodel',
            name='assigneeName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
