# Generated by Django 4.1.2 on 2022-10-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0005_annoucementmodel'),
        ('odyssey', '0006_alter_issuemodel_assigneeid_and_more'),
    ]

    operations = [
    ]
