# Generated by Django 4.1.2 on 2022-10-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0007_merge_20221018_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
