# Generated by Django 4.1.2 on 2022-10-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0008_issuemodel_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='issueName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
