# Generated by Django 4.1.2 on 2022-10-25 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0009_issuemodel_issuename'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='assignedIssue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odyssey.issuemodel'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='completedIssues',
            field=models.ManyToManyField(blank=True, related_name='completedIssues', to='odyssey.issuemodel'),
        ),
    ]
